apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: process-core-dev
spec:
  selector:
    name: core-mongo
    #clusterIP: None
  ports:
  - port: 27017
    targetPort: 27017
    #nodePort: 30001
    #  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  name: core-mongo
  namespace: process-core-dev
  labels:
      name: core-mongo
spec:
    hostname: mongo
    nodeSelector:
       kubernetes.io/hostname: bookcees 
    containers:
    - name: core-mongo
      image: mongo
      env:
      - name: MONGO_INITDB_ROOT_USERNAME
        valueFrom:
            secretKeyRef:
                name: vault
                key: db-root-user
      - name: MONGO_INITDB_ROOT_PASSWORD
        valueFrom:
            secretKeyRef:
                name: vault
                key: db-root-pass
      ports:
          - containerPort: 27017
      command:
          - mongod
          - --bind_ip_all
