apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: process-core
spec:
  selector:
    name: core-mongo
  ports:
  - port: 27017
    targetPort: 27017
---
apiVersion: v1
kind: Pod
metadata:
  name: core-mongo
  namespace: process-core
  labels:
      name: core-mongo
spec:
    hostname: mongo
    nodeSelector:
       kubernetes.io/hostname: bookcees 
    volumes:
        - name: volume-0
          hostPath:
            path: /mnt/mongo/db
    containers:
    - name: core-mongo
      image: mongo
      volumeMounts:
      - name: volume-0
        mountPath: /data/db
      env:
      - name: MONGO_INITDB_ROOT_USERNAME
        valueFrom:
            secretKeyRef:
                name: vault
                key: db-root-user
      - name: MONGO_INITDB_ROOT_PASSWORD
        valueFrom:
            secretKeyRef:
                name: vault
                key: db-root-pass
      ports:
          - containerPort: 27017
      command:
          - mongod
          - --bind_ip_all
