apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: process-core
spec:
  selector:
    name: core-mongo
  ports:
  - port: 27017
    targetPort: 27017
---
apiVersion: v1
kind: Pod
metadata:
  name: core-mongo
  namespace: process-core
  labels:
      name: core-mongo
spec:
    hostname: mongo
    containers:
    - name: core-mongo
      image: mongo
      env:
      - name: MONGO_USER_PASS
        valueFrom:
            secretKeyRef:
                name: vault
                key: dbpass
      - name: MONGO_INITDB_ROOT_USERNAME
        valueFrom:
            secretKeyRef:
                name: vault
                key: db-root-user
      - name: MONGO_INITDB_ROOT_PASSWORD
        valueFrom:
            secretKeyRef:
                name: vault
                key: db-root-pass
      ports:
          - containerPort: 27017
      command:
          - /bin/bash
          - -c
          - |
            mongod --bind_ip_all &
            sleep 5
            echo "db.createUser({'user':'core-infra', 'pwd':'$MONGO_USER_PASS', 'roles':['readWrite']});" > /tmp/mongosetup.js
            cat /tmp/mongosetup.js
            mongo process /tmp/mongosetup.js
            while [ 1 ]; do sleep 3600; done;
